env:
  browser: true
  commonjs: true
  es6: true
  amd: true
extends: 'plugin:vue/recommended'
plugins:
  - vue
  - prettier
settings:
  html/html-extensions:
  - ".html"
  - ".vue"
parserOptions:
  sourceType: module
  parser: "babel-eslint"
  ecmaVersion: 2017
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    -
      avoidEscape: true
  semi:
    - error
    - always
  no-console: 0
  no-debugger: 0
  vue/require-default-prop: 0
  vue/html-indent: 0
  max-len:
    - 1
    -
      code: 120
      ignoreUrls: true
  vue/html-self-closing:
    - error
    -
      html:
        void: 'any'
  vue/max-attributes-per-line:
    - 2
    -
      singleline: 120
      multiline:
        max: 2
        allowFirstLine: true
globals:
  window: true
  location: true
  document: true
  module: true
  __dirname: true
